# Generated by Django 2.2.10 on 2021-03-25 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, null=True, verbose_name='Название опроса')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания опроса')),
                ('date_end', models.DateTimeField(verbose_name='Дата окончания опроса')),
                ('description', models.TextField(null=True, verbose_name='Описание опроса')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2048, null=True, verbose_name='Текст вопроса')),
                ('is_active', models.BooleanField(default=False, verbose_name='Видимость для пользователя')),
                ('max_points', models.PositiveSmallIntegerField(null=True, verbose_name='Максимальное количество выборов вариантов')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='interview.Interview')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096, verbose_name='Название выбора')),
                ('points', models.PositiveSmallIntegerField(null=True, verbose_name='')),
                ('lock_other', models.BooleanField(default=False, verbose_name='')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='interview.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='interview.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
