# Generated by Django 2.2.10 on 2021-03-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ на вопрос', 'verbose_name_plural': 'Ответы на вопрос'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Выбор в вопросе', 'verbose_name_plural': 'Выборы в вопросе'},
        ),
        migrations.AlterModelOptions(
            name='interview',
            options={'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[(1, 'Ответ текстом'), (2, 'Ответ с выбором одного варианта'), (3, 'Ответ с выбором нескольких вариантов')], default=1, max_length=128),
        ),
        migrations.AlterField(
            model_name='interview',
            name='date_start',
            field=models.DateTimeField(verbose_name='Дата создания опроса'),
        ),
    ]
