# Generated by Django 2.2.10 on 2021-03-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20210326_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='max_points',
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[(1, 'Ответ текстом'), (2, 'Ответ с выбором одного варианта'), (3, 'Ответ с выбором нескольких вариантов')], default=1, max_length=128, verbose_name='Тип вопроса'),
        ),
    ]
