# Generated by Django 2.2.10 on 2021-03-26 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_auto_20210326_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='interview',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interview.Interview'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Ответ текстом'), ('one_choice', 'Ответ с выбором одного варианта'), ('some_choices', 'Ответ с выбором нескольких вариантов')], max_length=128, verbose_name='Тип вопроса'),
        ),
    ]
