# Generated by Django 2.2.10 on 2021-03-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_auto_20210326_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='points',
        ),
        migrations.AlterField(
            model_name='choice',
            name='lock_other',
            field=models.BooleanField(default=False, verbose_name='Заблокировать остальные?'),
        ),
    ]
