# Generated by Django 2.2.10 on 2021-03-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_auto_20210326_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(null=True, verbose_name='Текст вопроса'),
        ),
    ]
